services:

  #sensors
  iot-device-north-sensor:
    build:
        dockerfile: publisher.Dockerfile
    container_name: iot-device-north-sensor
    depends_on:
      - kafka
    environment:
      SENSOR_NO: "NORTH-SENSOR-001"
      SENSOR_TIME_SYNC: 5
    networks:
      - iot-net

  iot-device-south-sensor:
    build:
        dockerfile: publisher.Dockerfile
    container_name: iot-device-south-sensor
    depends_on:
      - kafka
    environment:
      SENSOR_NO: "SOUTH-SENSOR-001"
      SENSOR_TIME_SYNC: 10
    networks:
      - iot-net

  #consumer
  iot-consumer:
    build:
        dockerfile: consumer.Dockerfile
    container_name: iot-consumer
    depends_on:
      - kafka
    networks:
      - iot-net

  #databases
  iot-mongo:
    image: mongo:7.0
    container_name: iot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - iot-net


  #kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - iot-net

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - iot-net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.1
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    networks:
      - iot-net

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.1
    container_name: control-center
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
volumes:
  mongo_data: